name: ax-emote-bot

services:
  - name: ax-emote-server
    type: web
    instance_type: free
    ports:
      - port: 8000
        protocol: http
    routes:
      - path: /
        port: 8000
    env:
      - key: PORT
        value: "8000"
      - key: PYTHONUNBUFFERED
        value: "1"
    build:
      buildpack: python
    run:
      command: python main.py
    health_checks:
      - path: /
        port: 8000
        protocol: http
        initial_delay_seconds: 10
        period_seconds: 30
